# Generated by Django 5.0 on 2025-10-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_inn',
            field=models.CharField(blank=True, help_text='ИНН организации', max_length=20, null=True, verbose_name='organization INN'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization_name',
            field=models.CharField(blank=True, help_text='Наименование организации', max_length=255, null=True, verbose_name='organization name'),
        ),
    ]
